mod OpenMP

diff --git a/.github/workflows/build_static.yml b/.github/workflows/build_static.yml
--- a/.github/workflows/build_static.yml
+++ b/.github/workflows/build_static.yml
@@ -48,14 +48,26 @@ jobs:
       run: |
         brew install ${{ matrix.additional_packages }}
         echo "PATH=/opt/homebrew/opt/llvm@18/bin:$PATH" >> $GITHUB_PATH
-        export LDFLAGS="-L/opt/homebrew/opt/llvm@18/lib"
-        export CPPFLAGS="-I/opt/homebrew/opt/llvm@18/include"
-        echo "OpenMP_C_FLAGS=-I/opt/homebrew/opt/llvm@18/include -Xclang -fopenmp" >> $GITHUB_ENV
-        echo "OpenMP_CXX_FLAGS=-I/opt/homebrew/opt/llvm@18/include -Xclang -fopenmp" >> $GITHUB_ENV
-        echo "OpenMP_C_LIB_NAMES=omp" >> $GITHUB_ENV
-        echo "OpenMP_CXX_LIB_NAMES=omp" >> $GITHUB_ENV
-        echo "OpenMP_omp_INCLUDE=/opt/homebrew/opt/llvm@18/include" >> $GITHUB_ENV
-        echo "OpenMP_omp_LIBRARY=/opt/homebrew/opt/llvm@18/lib/libomp.dylib" >> $GITHUB_ENV
+
+    - name: Check for OpenMPConfig.cmake
+      if: startsWith(matrix.os, 'macos')
+      run: |
+        if [[ -f /opt/homebrew/opt/llvm@18/lib/cmake/openmp/OpenMPConfig.cmake ]]; then
+          echo "OpenMPConfig.cmake found!"
+        else
+          echo "OpenMPConfig.cmake not found!"
+          exit 1
+        fi
+
+    - name: Check for libomp.dylib
+      if: startsWith(matrix.os, 'macos')
+      run: |
+        if [[ -f /opt/homebrew/opt/llvm@18/lib/libomp.dylib ]]; then
+          echo "libomp.dylib found!"
+        else
+          echo "libomp.dylib not found!"
+          exit 1
+        fi
 
 
     - name: Set up build directory
@@ -74,12 +86,6 @@ jobs:
           -DDEFINE_CUDA=OFF \
           -S ${{ github.workspace }}
 
-    - name: Find omp.h
-      if: startsWith(matrix.os, 'macos')
-      shell: bash
-      run: |
-        find /opt/homebrew/opt/llvm@18 -name "omp.h" -print
-
     - name: Configure CMake (macOS)
       if: startsWith(matrix.os, 'macos')
       shell: bash
@@ -90,14 +96,7 @@ jobs:
           -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
           -DBUILD_SHARED_LIBS=OFF \
           -DDEFINE_CUDA=OFF \
-          -DCMAKE_INCLUDE_PATH="${{ env.OpenMP_omp_INCLUDE }}" \
-          -DCMAKE_LIBRARY_PATH="${{ env.OpenMP_omp_LIBRARY }}" \
-          -DOpenMP_C_FLAGS="${{ env.OpenMP_C_FLAGS }}" \
-          -DOpenMP_CXX_FLAGS="${{ env.OpenMP_CXX_FLAGS }}" \
-          -DOpenMP_C_LIB_NAMES="${{ env.OpenMP_C_LIB_NAMES }}" \
-          -DOpenMP_CXX_LIB_NAMES="${{ env.OpenMP_CXX_LIB_NAMES }}" \
-          -DOpenMP_omp_INCLUDE="${{ env.OpenMP_omp_INCLUDE }}" \
-          -DOpenMP_omp_LIBRARY="${{ env.OpenMP_omp_LIBRARY }}" \
+          -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/llvm@18 \
           -S ${{ github.workspace }}
 
     - name: Configure CMake (Windows)
